# Generated by Django 2.0.1 on 2019-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('subarea', models.CharField(max_length=100)),
                ('anniversary', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
