# Generated by Django 2.0.1 on 2019-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.TextField(default='DD nagar'),
            preserve_default=False,
        ),
    ]
