# Generated by Django 2.0.1 on 2019-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190221_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.CharField(default='ritesh', max_length=255),
            preserve_default=False,
        ),
    ]
