# Generated by Django 2.0.1 on 2019-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='senderid',
            field=models.CharField(default='websms', max_length=6),
            preserve_default=False,
        ),
    ]
